### ISSUE TITLE
Require stable Nim?

### ISSUE THREAD

**Issue by PMunch** [beef331/fungus#1]
Not sure if this actually needs the devel version of Nim, but I suspect you just did `nimble init` while having it selected. Would be nice to have a stable release as the target.

**Comment by beef331** [comment]
There are a multitude of reasons why 1.6.x is not supported:
- `CacheTable.contains`. Could be implemented as an iteration, not a big problem.
- `Branch: tuple[a, b: C]` does not compile could change to `Branch = tuple[a, b: C]`, not a big problem
- After implementing the above simple examples fail on CGen, very big problem.
